insert into products (name, seller_name, price) values ('Doilies - 8, Paper TEST', 'Vimbo', 912881.91);
insert into products (name, seller_name, price) values ('Cheese - Feta TEST', 'Brightbean', 958734.73);
insert into products (name, seller_name, price) values ('Milk Powder TEST', 'Jaxspan', 697447.95);
insert into products (name, seller_name, price) values ('Pineapple - Canned, Rings TEST', 'Rhyloo', 580313.1);
insert into products (name, seller_name, price) values ('Muffin Batt - Carrot Spice TEST', 'Browsebug', 453904.94);
insert into products (name, seller_name, price) values ('Cookie - Oatmeal TEST', 'Blogpad', 320526.11);
insert into products (name, seller_name, price) values ('Cinnamon - Ground TEST', 'Mita', 175298.57);
insert into products (name, seller_name, price) values ('Mcgillicuddy Vanilla Schnap TEST', 'Voonder', 454264.17);
insert into products (name, seller_name, price) values ('Coke - Classic, 355 Ml TEST', 'Skipfire', 892912.88);
insert into products (name, seller_name, price) values ('Wine - Balbach Riverside TEST', 'Realcube', 191347.65);
insert into products (name, seller_name, price) values ('Pate - Liver TEST', 'Agimba', 6863.13);
insert into products (name, seller_name, price) values ('Bread - Rolls, Corn TEST', 'Voomm', 134717.6);
insert into products (name, seller_name, price) values ('Sea Bass - Fillets TEST', 'Fliptune', 854853.06);
insert into products (name, seller_name, price) values ('Wine - Lamancha Do Crianza TEST', 'Ailane', 287306.19);
insert into products (name, seller_name, price) values ('Nut - Walnut, Pieces TEST', 'Ooba', 333253.59);
insert into products (name, seller_name, price) values ('Onions - White TEST', 'Blognation', 989423.05);
insert into products (name, seller_name, price) values ('Tarragon - Fresh TEST', 'Buzzbean', 387142.29);
insert into products (name, seller_name, price) values ('Mushroom - Trumpet, Dry TEST', 'Zoomzone', 2992.04);
insert into products (name, seller_name, price) values ('Nut - Macadamia TEST', 'Vinder', 765189.07);
insert into products (name, seller_name, price) values ('Pasta - Lasagne, Fresh TEST', 'Realcube', 648758.53);
insert into products (name, seller_name, price) values ('Blouse / Shirt / Sweater TEST', 'Zava', 454342.46);
insert into products (name, seller_name, price) values ('Juice - Apple Cider TEST', 'Viva', 100429.21);
insert into products (name, seller_name, price) values ('Vodka - Lemon, Absolut TEST', 'Edgeclub', 177040.5);
insert into products (name, seller_name, price) values ('Soup - Campbells Chicken TEST', 'Riffwire', 859121.44);
insert into products (name, seller_name, price) values ('Salami - Genova TEST', 'Shufflester', 760631.51);
